import Link from 'next/link';
import ProprStatsLogo from '../../../components/ProprStatsLogo';

export const metadata = {
  title: 'Terms of Service',
  description: 'ProprStats Terms of Service — please read before using the platform.',
};

const EFFECTIVE_DATE = 'April 6, 2026';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Nav */}
      <nav className="border-b border-white/5 bg-gray-950/80 backdrop-blur-xl px-4 sm:px-8 py-4">
        <div className="mx-auto max-w-4xl flex items-center justify-between">
          <Link href="/" className="flex items-center">
            <ProprStatsLogo variant="light" size={28} />
          </Link>
          <Link href="/" className="text-sm text-gray-400 hover:text-white transition-colors">← Back to home</Link>
        </div>
      </nav>

      <main className="mx-auto max-w-4xl px-4 sm:px-8 py-16">
        <div className="mb-10">
          <h1 className="text-3xl font-black text-white mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500">Effective date: {EFFECTIVE_DATE}</p>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-gray-400 leading-relaxed">

          {/* Disclaimer banner */}
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-5">
            <p className="text-sm font-semibold text-amber-400 mb-1">Important Disclaimer</p>
            <p className="text-sm text-amber-300/80">
              ProprStats provides statistical analysis and research tools for informational and entertainment purposes only.
              Nothing on this platform constitutes gambling advice, financial advice, or any recommendation to place a wager.
              Past model performance does not guarantee future results. Always gamble responsibly and within your means.
            </p>
          </div>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using ProprStats (the &ldquo;Service&rdquo;) operated by ProprStats (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;),
              you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              ProprStats is a baseball analytics platform that provides statistical models, prop projections, and research tools
              related to Major League Baseball. The Service is intended solely for informational and research purposes. We do not
              offer, facilitate, or promote gambling or wagering of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">3. No Gambling Advice</h2>
            <p>
              All scores, projections, EdgeScore ratings, LineCheck results, and other outputs generated by ProprStats are
              statistical estimates based on publicly available data. They are provided for informational purposes only and do not
              constitute advice to place any bet or wager. ProprStats makes no representation that any particular outcome will occur.
              You acknowledge that sports betting involves substantial risk of loss and that you assume full responsibility for any
              decisions you make based on information from this Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">4. Eligibility</h2>
            <p>
              You must be at least 18 years of age (or the legal age of majority in your jurisdiction) to use this Service.
              By using the Service, you represent and warrant that you meet this requirement. Users in jurisdictions where online
              gambling-related content is prohibited are responsible for determining whether their access to the Service is lawful.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">5. User Accounts</h2>
            <p>
              When you create an account, you agree to provide accurate and complete information. You are responsible for
              maintaining the confidentiality of your account credentials and for all activity that occurs under your account.
              You agree to notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">6. Subscriptions and Payments</h2>
            <p>
              Paid subscription plans are billed in advance on a monthly or annual basis. Subscriptions automatically renew unless
              cancelled before the renewal date. You may cancel your subscription at any time through your account settings. No
              refunds are provided for partial billing periods, except where required by applicable law. We reserve the right to
              modify pricing with 30 days&apos; notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">7. Intellectual Property</h2>
            <p>
              All content, models, trademarks (including EdgeScore™, LineCheck™, ProbMap™, TrueContact™, PlatoonIQ™, and
              MatchupFile™), and software on the Service are owned by ProprStats or its licensors. You may not reproduce,
              distribute, or create derivative works from any content on the Service without our express written permission.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">8. Prohibited Uses</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
              <li>Use the Service to operate or promote any gambling service</li>
              <li>Scrape, crawl, or systematically extract data from the Service</li>
              <li>Attempt to reverse-engineer or copy our statistical models</li>
              <li>Use the Service in any manner that violates applicable laws</li>
              <li>Share account credentials or provide access to unauthorized users</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">9. Data Sources and Accuracy</h2>
            <p>
              ProprStats sources data from publicly available sources including the MLB Stats API, Baseball Savant, and Open-Meteo.
              While we strive for accuracy, we make no warranty that data is complete, current, or error-free. Statistical models
              are inherently probabilistic and will not always produce accurate predictions. We are not liable for any decisions
              made based on data or projections from this Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">10. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
              NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">11. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, PROPRSTATS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA, OR GAMBLING LOSSES,
              ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">12. Responsible Gambling</h2>
            <p>
              If you choose to engage in sports wagering, please do so responsibly. Resources are available if you or someone you
              know may have a gambling problem:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
              <li>National Problem Gambling Helpline: 1-800-522-4700</li>
              <li>National Council on Problem Gambling: <span className="text-blue-400">ncpgambling.org</span></li>
              <li>Gamblers Anonymous: <span className="text-blue-400">gamblersanonymous.org</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">13. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other
              reason at our sole discretion. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">14. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. We will notify registered users of material changes via email or a notice on
              the Service. Your continued use of the Service after changes become effective constitutes your acceptance of the
              revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">15. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the jurisdiction in which ProprStats operates, without regard to conflict
              of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">16. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:support@proprstats.com" className="text-blue-400 hover:text-blue-300 transition-colors">
                support@proprstats.com
              </a>
            </p>
          </section>

        </div>

        {/* Footer links */}
        <div className="mt-12 pt-8 border-t border-white/5 flex flex-wrap gap-4 text-sm text-gray-600">
          <Link href="/legal/privacy" className="hover:text-gray-400 transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-gray-400 transition-colors">← Home</Link>
        </div>
      </main>
    </div>
  );
}
