// Serves the pre-cached pp-lines.json generated by GitHub Actions cron (hourly).
// GH Actions IPs are not blocked by PrizePicks; Render/Vercel datacenter IPs are.
import { readFileSync } from 'fs';
import { join } from 'path';

export const runtime = 'nodejs';

export async function GET() {
  try {
    const filePath = join(process.cwd(), 'public', 'pp-lines.json');
    const raw = readFileSync(filePath, 'utf8');
    return new Response(raw, {
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, s-maxage=1800, stale-while-revalidate=3600',
      },
    });
  } catch {
    return Response.json({ error: 'PP cache not available', lines: {} }, { status: 503 });
  }
}
